### ISSUE TITLE
Issue when creating author. 

### ISSUE THREAD

**Issue by emilva** [duo-labs/journal-cli#4]
Hi,

I am getting this stacktrace when I try to create an author, maybe there is some mixup with python 2 vs 3?

```  journal author --name "Emil Vaagland" --avatar avatar.jpeg emil-vaagland
Setting up the author for emil-vaagland
Traceback (most recent call last):
  File "/Users/e/source/github.com/journal-cli/journal", line 6, in <module>
    cli()
  File "/Users/e/homebrew/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/e/homebrew/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/e/homebrew/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/e/homebrew/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/e/homebrew/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/e/source/github.com/journal-cli/commands/author.py", line 101, in author
    create_author(username, name, avatar)
  File "/Users/e/source/github.com/journal-cli/commands/author.py", line 78, in create_author
    os.makedirs(author_path, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'```

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out!

This is indeed a Python 2 compatibility issue. Right now, Journal is written to support Python 3. Since we use Py3 internally, I'm afraid I don't see us being able to put in the development time to support compatibility with Py2.

Sorry we couldn't be of more help here!

**Comment by emilva** [comment]
Thanks for the reply @jordan-wright!

Of course, I do not expect you to make it python 2 compatible, but I think it would help the adoption of the tool if you specified in the install instructions that you need to use python3. I am not a pythonista, and my local python installation(s) are messy.  For me I think `pip install` defaults to python 2.
